In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [3]:
df['Actor'] ## Single column (as Series)

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [4]:
df[['Actor' , 'Film']]  #Multiple columns (as DataFrame)

                 Actor                      Film
0       Shah Rukh Khan                   Pathaan
1          Salman Khan           Tiger Zinda Hai
2           Aamir Khan                    Dangal
3        Ranbir Kapoor                Brahmastra
4        Ranveer Singh                 Padmaavat
5   Ayushmann Khurrana                 Andhadhun
6        Rajkummar Rao                     Stree
7       Hrithik Roshan                       War
8         Akshay Kumar                Good Newwz
9        Kartik Aaryan         Bhool Bhulaiyaa 2
10        Varun Dhawan     Badrinath Ki Dulhania
11       Vicky Kaushal  Uri: The Surgical Strike

In [5]:
df.loc[0]  # First row (by row labels)

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [6]:
df.iloc[0] # First row (by position basically index)

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [7]:
df.loc[0:2 , ['Actor' , 'IMDb' , 'Film' ]]

            Actor  IMDb             Film
0  Shah Rukh Khan   7.2          Pathaan
1     Salman Khan   6.0  Tiger Zinda Hai
2      Aamir Khan   8.4           Dangal

In [8]:
df.iloc[0:2 , 0:2]

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

In [9]:
df.at[0, "Actor"]       # Fast label-based access

'Shah Rukh Khan'

In [10]:
df.iat[0, 1]           # Fast position-based access

'Pathaan'

In [11]:
df[df['IMDb']>7]['Actor']

0         Shah Rukh Khan
2             Aamir Khan
5     Ayushmann Khurrana
6          Rajkummar Rao
11         Vicky Kaushal
Name: Actor, dtype: object

In [12]:
df[(df['IMDb']>6) & (df['Year']>2018)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [13]:
df.query("Year > 2018 and IMDb > 6")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [14]:
#Dynamic column names:   (like this)
#col = "Age"
#df.query(f"{col} > 25")

In [15]:
# can use @ to reference Python variables
#To pass external variables into .query():
#LIKE THIS->
#age_limit = 30
#df.query("age > @age_limit")

In [16]:
#CHAINED COMPARISIONS
df.query("7.2<IMDb<8.4")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [17]:
#.copy() helps in copying a edited data when assigned to a real data (to make sure the original data doesnt gets manipulated)

In [18]:
#.query() returns a copy, not a view
#The result is a new DataFrame. Changes won't affect the original unless reassigned:
#filtered = df.query("age < 50")